### ISSUE TITLE
Question: how to estimate variance of AIPW estimate of population mean using GRF?

### ISSUE THREAD

**Issue by thomasklausch2** [grf-labs/grf#380] opened 2019-03-17 17:52 UTC
My objective is to estimate the population (or sample) mean of `y` where `y` is only partly observed; that is `y[W==1]` where `W` is binomial dependent on `X` and `y` also depends on `X`. This problem is the classical missing data problem when estimating means where `y` is missing at random (MAR). The problem is extended to a causal inference problem, when `y1` is observed under treatment `W==1` when `W==1` and else, under treatment `W==0`, `y0` is observed . Now `y = W*y1 + (1-W)*y0` where `y1` and  `y0` the potential outcomes under the two treatments. Then  `causal_forest` can be used to estimate treatment effects conditional on `X`. Also in this scenario it may be the goal to estimate the population mean of `y1` or `y0`, e.g. E(y1). This is a classical causal inference problem. 

My question is how to estimate `mu1 = E(y1)` using the semi-parametric augmented inverse propensity estimator in the missing at random setting (i.e., no outcomes are observed when `W==0`). This estimator is given by `mu1 = mean(phi_i)`  where `phi_i =  W_i/e(Xi) * (y-mu1(Xi))+mu1(Xi)` and  `e(Xi)` and `mu1(Xi)` are (out-of-bag) predictions of the treatment propensity and outcome from regression forests using `grf`.

My problem is, in detail, how the variance of `mu1` should be estimated. In particular it seems that a sandwich estimator for `mu1` is `V  = sum((phi_i - mu1)^2)/(n-1)^2`. Now, I tried to estimate `E(y1)` in two settings:

1. Only `y1` is observed where some data is missing (e.g. unit non-response)
2. Also `y0` is observed where `y1` is missing (i.e. causal inference problem)

In setting 2 I estimate the model using `causal_forest` and use out of bag predictions of `m` and `e` from from this function to derive estimates of `mu1`. However, in setting 1 this does not work, because  `y0` is not observed. Therefore `regression forest` is used instead on the observed part of `y1`. Subsequently, `predict` is used to get predictions `mu1` of `y1` where `W==0` and out of bag predictions from regression forest object are used for the part of the data where `W==1`. I study the coverage of the true mean. Unfortunately, only the second strategy/setting works; the estimator under the first setting has larger bias and insufficient coverage. Is there a way to do the estimation also in the unit nonresponse setting, that is when there is no `y0`?

Here is the code (based on a simulation code snippet provided by Stefan Wager):

```
library(grf)

## Determine population mean
n = 10^7
p = 2
X = matrix(rnorm(n*p), n, p)
mu0 = pmax(X[,1] + X[,2], 0)
tau = 0
Y = mu0 + tau
pmean = mean(Y)
rm(Y,X,mu0)
##

n          = 400
q          = 10
iterations = 100

reps = replicate(iterations, {
  x   = matrix(rnorm(n*q), n, q)
  mu0 = pmax(x[,1] + x[,2], 0)
  y   = mu0 + rnorm(n)
  p   = 1/(1 + exp(-(x[,1] + x[,2])/2))
  
  # Create sample selection
  W    = rbinom(n,1,p)
  d.x  = data.frame(y,x)
  d1.x = d.x[W==1,]
  ord  = 1:n
  
  # Intuitive approach to AIPW when y0 is not observed (using d1.x)
  # Use generalised / honest random forests to estimate outcome and propensity score models
  y.m.cor  = regression_forest(Y=d1.x$y, X=as.matrix(d1.x[,2:(q+1)]), num.trees = 2000, tune.parameters = F)
  pi.m.cor = regression_forest(Y=W, X=x, num.trees = 2000, tune.parameters = F)
  # Predict on all data (x)
  pred.y  = predict(y.m.cor, x)
  pred.pi = predict(pi.m.cor, x)
  
# use OOB prediction from regression_forest where y is observed (W==1), and predictions by predict where y is not observed (W==0)
  mu1 = c(y.m.cor$predictions, pred.y$predictions[W==0])
  mu1 = mu1[order(c(i[W==1],i[W==0]))] #reorder to original order
  e = pi.m.cor$predictions
  
#AIPW
  phi     = W/e*(y-mu1)+mu1
  mu.rf   = mean(phi)
  V.rf    = sum((phi-mu.rf)^2)/(n-1)^2
  
  # Causal forest approach by Stefan Wager
  cf       = causal_forest(x, y, W)
  mu1        = cf$Y.hat + (1 - cf$W.hat) * cf$predictions
  e        = cf$W.hat
  phi      = W/e*(y-mu1)+mu1
  mu.cf = mean(phi)
  V.cf  = sum((phi-mu.cf)^2)/(n-1)^2

  c(mu.rf = mu.rf, Z.rf= (mu.rf-pmean)/sqrt(V.rf),mu.cf = mu.cf, Z.cf= (mu.cf-pmean)/sqrt(V.cf))
})

par(mfrow=c(1,2))
qqnorm(reps["Z.rf",], main="QQ-regression forest"); abline(0, 1)
qqnorm(reps["Z.cf",], main="QQ-causal forest"); abline(0, 1)

q = qnorm(0.975)
er.rf = mean(reps["Z.rf",] > q)
er.cf = mean(reps["Z.cf",] > q)

# Type 1 error
er.rf; er.rf- q*sqrt(er.rf*(1-er.rf)/iterations) # Type 1 error and lower CI bound
er.cf; er.cf- q*sqrt(er.cf*(1-er.cf)/iterations)

# Bias
mean(reps["mu.rf",]) - pmean
mean(reps["mu.cf",]) - pmean
```

**Comment by swager** [comment] 2019-03-18 19:13
In general, everything looks fine to me here; however, the two following lines don't run on my machine (`i` is not defined):
```
mu1 = c(y.m.cor$predictions, pred.y$predictions[W==0])
mu1 = mu1[order(c(i[W==1],i[W==0]))] #reorder to original order
```
The goal of these lines is to collect predictions of E[Y|X=x, W=1] from a regression forest trained on (X, Y) pairs with W=1. These predictions need to be out-of-bag when W=1, whereas the set of X with W=0 can be seen as a test set. I re-wrote those lines as:
```
mu1 = pred.y$predictions
mu1[W==1] = y.m.cor$predictions
```
Now, everything seems OK. The causal forest approach is a little more accurate, but that's to be expected (as it can also use outcome information on W=0 to learn about the underlying main effects):
```
> # Bias
> mean(reps["mu.rf",]) - pmean
[1] 0.05876641
> mean(reps["mu.cf",]) - pmean
[1] 0.04657706
> 
> # MSE
> mean((reps["mu.rf",] - pmean)^2)
[1] 0.009604598
> mean((reps["mu.cf",] - pmean)^2)
[1] 0.008063624
```

**Comment by swager** [comment] 2019-03-18 19:17
Also, as seen in the QQ plot of the Z-scores, the variance estimates seem OK here. (The confidence intervals are of course noticeably off-center, but the sample size of `n=400` is also quite small.)

[qqplot.pdf](https://github.com/grf-labs/grf/files/2979882/qqplot.pdf)

**Comment by jtibshirani** [comment] 2019-04-07 23:27
I'm closing this out because it seems like your question is addressed, feel free to email or open a different issue if something else comes up.

**Closed by jtibshirani** 2019-04-07 23:27 UTC
Labels: question
