### ISSUE TITLE
number of trees in local centering step 

### ISSUE THREAD

**Issue by klosins** [grf-labs/grf#270] opened 2018-08-01 23:56 UTC
Hey guys,

I was thinking that we may want to give users an option to specify the number of trees used in the local centering step. I thought the parameter could num.lc.trees. The default could be still be min(num.trees, 500)), keeping the current number of trees.

```r
causal_forest <- function(X, Y, W,
                          Y.hat = NULL,
                          W.hat = NULL,
                          sample.fraction = 0.5,
                          mtry = NULL,
                          num.trees = 2000,
                          num.threads = NULL,
                          min.node.size = NULL,
                          honesty = TRUE,
                          ci.group.size = 2,
                          alpha = NULL,
                          imbalance.penalty = NULL,
                          stabilize.splits = TRUE,
                          compute.oob.predictions = TRUE,
                          seed = NULL,
                          clusters = NULL,
                          samples_per_cluster = NULL,
                          tune.parameters = FALSE,
                          num.lc.trees = min(num.trees, 500), 
                          num.fit.trees = 200,
                          num.fit.reps = 50,
                          num.optimize.reps = 1000) 
```

Should I submit a PR? Thanks

**Comment by jtibshirani** [comment] 2018-08-03 05:08
Hi @klosins, I'm curious about the motivation for this addition. Have you noticed cases where the default of `min(num.trees, 500)` provides poor performance, and we could have selected a better heuristic? Expert users can already pass in `Y.hat` and `W.hat` to bypass the local centering calculation, so if they feel strongly that a different number of trees would help, they could always train the regression forests themselves.

I'm digging into the motivation because we try to avoid adding new parameters unless they have a strong use case (as you can see, the parameter lists are already quite long!)

**Comment by susanathey** [comment] 2018-08-03 05:10
In principle there is no reason that the number of trees for local centering should be the same as the causal forest, but I agree that expert users can bypass.

**Comment by halflearned** [comment] 2018-08-03 06:26
Well, maybe this is motivated more by design than by performance. As a user of grf:

1) I felt betrayed when I realized that `grf` had been _silently_ capping the number of trees in this step at 500 all along. (`grf`, I thought we were friends!)

2) Whenever I do want to bypass this, I have to write

```r
forest.Y <- grf::regression_forest(X=X, Y=Y, num.trees=2000)
forest.W <- grf::regression_forest(X=X, Y=W, num.trees=2000)
Y.hat <- predict(forest.Y, estimate.variance=FALSE)$predictions 
W.hat <- predict(forest.W, estimate.variance=FALSE)$predictions 
cf <- grf::causal_forest(X=X, Y=Y, W=W, Y.hat=Y.hat, W.hat=W.hat, num.trees=5000)
```

which is considerably more verbose than a hypothetical

```r
cf <- grf::causal_forest(X=X, Y=Y, W=W,  num.trees=5000, num.local.centering.trees=2000)
```

---

That said, I appreciate that the signature is already kind of long. So if we label this one `wontfix`, we should update the documentation to explicit state what's going on. Something like:

> Estimates of the expected responses E[Y | Xi], marginalizing over treatment. If Y.hat = NULL, these are estimated using a separate regression forest **of size min(500, num.trees)**. See section 6.1.1 of the GRF paper for further discussion of this quantity.

**Comment by jtibshirani** [comment] 2018-08-04 00:38
Uh oh, we really don't want users to feel betrayed! Is there a default you would find more sensible/ straightforward? Perhaps just using `num.trees` directly, or some increasing function of `num.trees`?

**Comment by susanathey** [comment] 2018-08-04 00:56
I'm not sure why the max was there to start with, I think users would be most likely to expect num.trees to be used in all cases, but if they want to fine-tune then they can get verbose and do things manually.

**Comment by swager** [comment] 2018-08-04 03:05
The thought behind defaulting to a smaller number of trees for the nuisance components than for tau was that orthogonal moments theory suggests that being very accurate in the nuisance components isn't as important as being very accurate in the last step.

I agree that having the cap at 500 in there is a little awkward, though. I like the suggestion of @jtibshirani of using some increasing function of n.trees. Maybe max{100, n.trees / 10} or max{100, sqrt(n.trees)}? It'd be interesting to know how low we can go without hurting accuracy, because this is a pretty big cost in terms of computational effort.

**Comment by susanathey** [comment] 2018-08-04 03:12
I don't think we should assume that asymptotic theory has kicked in on a dataset of arbitrary size--people could be running this with hundreds of observations-- and in many cases getting the right answer is more important than finishing quickly.

**Comment by susanathey** [comment] 2018-08-04 21:45
Sure-so I think having default values of something like 2000-2000-2000 or 3000-2000-2000 would be good, but probably a simulation study that shows the monte carlo error of different values would be good.  I think Vitor's complaint though was that he told grf he wanted 5000 trees, and it overrode his preference and gave 500 each to the mu hat and e hat without warning him it was doing so.  On reflection, from a user perspective, I'd think there should be inputs for trees for m and e as well as the overall, and if the user doesn't set values for m and e, they would expect the same number of trees for all forests.  They would not expect 500 trees for m and e if they set 5000 in the input.

**Comment by susanathey** [comment] 2018-08-04 21:49
Another comment on the "ideally user chooses compute time" -- that is not usually how I would think about it, I would think that the user might choose the acceptable monte carlo error and try to achieve that, and then revisit this if it is taking too long, by reviewing a monte carlo error convergence curve.  If we can union forests, then the user could also specify time limit, look at convergence curve, and then decide to keep going.  For most applied projects, you are willing to compute hours or even a few days to get the right answer.  Only for simulation studies would you be very sensitive to modest differences in performance.

**Comment by halflearned** [comment] 2018-08-05 22:12
Ok, I discussed this with @klosins and we'll start a preliminary simulation study tomorrow, following what @jtibshirani and @susanathey have written. In particular we'll check for differences between the following schemes for local centering:

+ `num.trees` (i.e. use the same number of trees everywhere)
+ `max(100, num.trees / 10)`
+ `max(100, sqrt(num.trees))`
+ `min(500, num.trees)`

As for the simulation setups, we'll use the simulators in [causal-benchmark](https://github.com/swager/causal-benchmark) repo written by Jonathan and myself.

**Comment by halflearned** [comment] 2018-08-06 05:26
Will do!

**Closed** 2019-06-24 20:12 UTC
Labels: 1.0 release, feature, good first issue
