### ISSUE TITLE
Different split depths across v0.9.6-v0.10.1

### ISSUE THREAD

**Issue by pmeloni** [grf-labs/grf#312] opened 2018-10-06 20:37 UTC
Hi!,
I've been running a causal forest on some experimental data with the 9.6 version of grf and recently switched to the 10 and 10.1 versions but seem to be getting a max depth in splits of 1 as compared to the 21 splits I got with the 9.6 version. As a consequence, the results are also very different, with the ones I get with the 9.6v closer to those in other literature. I also tried changing the default parameters in the newer version to those of the old one but still keep on getting the same behavior in terms of splits. Given that I residualize prior to running the forest, I set Y.hat and W.hat to 0 to recreate the behavior of the precompute.nuisance parameter when set to FALSE. The code I'm running for v0.9.6 is:

[Github_example.R.zip](https://github.com/grf-labs/grf/files/2453390/Github_example.R.zip)

For v0.10-v0.10.1 the only difference is the causal forest function, either setting the default parameters to those of v 0.9.6 (with the exception of those I define in the older version as well) or as below:

```r

sample.fraction<-0.2
num.trees<-10000
min.node.size<-5000

print("Running forest")
tau.forest = causal_forest(X,Y,W,Y.hat = 0, W.hat = 0, sample.fraction = sample.fraction,
                           num.trees = num.trees, min.node.size = min.node.size,
                           honesty = TRUE, ci.group.size = 2)
```
I know that there's been a lot of changes from v0.9.6 to the newer ones, would you know if there are any parameters I should set differently?

**Comment by jtibshirani** [comment] 2018-10-07 06:41
Hi @pmeloni, this is definitely unexpected, as we didn't make major changes to the algorithm or to default parameters between 0.9.6 and 0.10.0. Would it be possible to provide us with the data as well so we could reproduce the issue + investigate (perhaps through email, if that would be preferable for you?) The `min.node.size` you're providing is relatively high, so I'm assuming the dataset is fairly large.

One point of clarification: are you seeing this difference when switching between 0.9.6 and 0.10.0, or only when comparing 0.9.6 to 0.10.1? Knowing this will help us narrow in on what changes might be causing the issue.

**Comment by pmeloni** [comment] 2018-10-10 20:02
Hi @jtibshirani,
Thank you for the response, I've sent the data. As for the versions, I ran the forest versions 0.9.6 and 0.10.0 with the full data and 0.10.1 with a reduced sample. The split depth difference takes place between versions 0.9.6 and 0.10.0 and with version 0.10.1 with the reduced sample I get the same behavior as with version 0.10.0.

**Comment by jtibshirani** [comment] 2018-10-11 17:12
Thanks @pmeloni, I will take a look and loop back with what I find.

**Comment by jtibshirani** [comment] 2018-10-15 01:13
I went to run the script `Github_example.R` with the data that you sent over email, and got an error in one of the data preprocessing steps. Would you be able to send a minimal working example that reproduces the issue?

I wanted to add one note in case it helps with troubleshooting. In 0.9.6, we began to require that each leaf node in a causal forest contain at least `min.node.size` treated and control samples (explained in https://github.com/grf-labs/grf/blob/master/REFERENCE.md#selecting-balanced-splits). With a large, fixed `min.node.size`, this change could cause the trees to be much shallower as you're seeing. However, the change was made in 0.9.6, and so it would show up in an upgrade to that version, not 0.10.0.

**Comment by pmeloni** [comment] 2018-10-15 19:45
I had attached the updated version of the R file to the email together with the data, but I apologize for the mix-up. 
Just in case the minimal working example is:

[Github_example.R.zip](https://github.com/grf-labs/grf/files/2480023/Github_example.R.zip)

It seems that the server on which the forest was running was loading v 0.9.5 instead of v 0.9.6 as I had previously thought, so your note is helpful. I'll try re-tuning the forest, although I would have thought that with  ~700,000 obs. the split depth would still be greater than 1.

**Comment by jtibshirani** [comment] 2018-10-15 23:10
Thanks, I see it now -- my mistake for missing it!

Good to know that the difference is actually between 0.9.5 and newer versions. To test the theory that the new interpretation of `min.node.size` is causing the discrepancy, you could try setting `stabilize.splits = FALSE` in the newer versions. This will fall back to the old behavior, and if our theory is right, you should see roughly the same split depths as in 0.9.5.

**Comment by pmeloni** [comment] 2018-10-20 22:02
Thank you @jtibshirani, indeed with ```stabilize.splits = FALSE``` I get a greater split depth. In the case where the treatment variable is residualized prior to the forest or W.hat is set to NULL and the treatment variable is not binary, how is the min.node.size restriction on the splitting rule applied?  Our data a high treatment propensity so in determining whether the ```stabilize.splits = TRUE``` behavior is preferable to the old splitting behavior this would play a big role.

As an aside, I noticed that the REFERENCE page says that the algorithm for the tuning function is still being finalized, but the comments on it also say .1 release and it runs even though the distribution output appears rather normal (no heterogeneity) as compared to other parameter definitions, is it actually already operational?

**Comment by jtibshirani** [comment] 2018-10-21 06:16
The exact algorithm for enforcing `min.node.size` is as follows:
- Take the average of the parent node's treatment values.
- When considering a split, we require that each child node have `min.node.size` samples with treatment value less than the average, and also that many samples with treatment value greater than or equal to the average.

This same approach is used when the treatment is binary, or when it (or the orthogonalized treatment) is continuous. We'll plan to update the reference with this information, as the current description is an oversimplification.

As for tuning, we've completed a first version of the algorithm that works well in many cases. However, we've encountered some instability in the optimization procedure that can cause the training procedure to crash.. We're working on solidifying the implementation, and are tracking the issue in https://github.com/grf-labs/grf/issues/278. Let me know if that answers your question (I may be missing part of what you're asking).

**Comment by pmeloni** [comment] 2018-10-25 02:48
Thank you @jtibshirani, it does, I think its not working well currently for our data so I am trying to customize the tuning in R by running some forest iterations with different parameters and evaluating the OOB. For this, I saw that there's the ```OptimizedPredictionStrategy#compute_debiased_error``` function but it cannot be called from R and I'm not an expert on C++. Would there be a way of exposing the function without running the tuning function?

**Comment by jtibshirani** [comment] 2018-10-25 05:04
The debiased error estimates should be returned as part of the OOB predictions in R, as `predictions$debiased.error`. I'm going to close this issue since we seem to have resolved the original question (differences in split depths), but please feel free to file another issue or send an email with additional questions.

**Closed by jtibshirani** 2018-10-25 05:04 UTC
Labels: question
