### ISSUE TITLE
out-of-sample ATE

### ISSUE THREAD

**Issue by adeldaoud** [grf-labs/grf#350] opened 2018-12-11 22:41 UTC
If you are filing a bug report, please consider using the following template.

**Description of the bug**
A)
I understand that the average_treatment_effect calculate the effect based on out-of-bag sample. However, what if I would like to calculate the out-of-sample effect? This could, for example, be useful when I have new data flowing in. See toy code below. 

B)
At an analytical level, would we even expect that the out-of-sample effect is different from the out-of-bag?

**Steps to reproduce**
```

## Not run:
# Find the optimal tuning parameters.
n = 50; p = 10
X = matrix(rnorm(n*p), n, p)
W = rbinom(n, 1, 0.5)
Y = pmax(X[,1], 0) * W + X[,2] + pmin(X[,3], 0) + rnorm(n)

# train and test (out-of-sample) split
training <- sample(1:NROW(X), NROW(X)*0.8) 
testing <- which(!1:NROW(X) %in% training)

# tune
tune_causal_forest(X[training, ], Y[training], W[training])
params = tune_causal_forest(X, Y, W)$params

# Use these parameters to train a regression forest.
tuned.forest = causal_forest(X[training, ], Y[training],  W[training], num.trees = 1000,
                             min.node.size = as.numeric(params["min.node.size"]),
                             sample.fraction = as.numeric(params["sample.fraction"]),
                             mtry = as.numeric(params["mtry"]),
                             alpha = as.numeric(params["alpha"]),
                             imbalance.penalty = as.numeric(params["imbalance.penalty"]))
                             
## End(Not run)

# out-o-bag
average_treatment_effect(tuned.forest)

# out-of-sample?
average_treatment_effect(tuned.forest, subset = testing)

```

**GRF version**
grf_0.10.2

**Comment by swager** [comment] 2018-12-15 04:04
The question of what we're trying to estimate here requires some careful definitions. This paper, https://davidahirshberg.bitbucket.io/static/minimax-linear.pdf, considers the problem of ``transporting'' average treatment effect estimates from one sample to another. How best to do this in the context of causal forests is an interesting question.

Also, note that if you just want to predict treatment effects at a new set of points `X.test`, you can call `predict(tuned.forest, X.test)`. A rough but simple estimate of the average effect over `X.test` could just average those predictions.

This issue is a duplicate of #129, so I'm closing it (but happy to continue the discussion on #129).

**Closed by swager** 2018-12-15 04:04 UTC
Labels: question
