### ISSUE TITLE
HPC node starting many threads despite setting num.threads = 1

### ISSUE THREAD

**Issue by janewliang** [grf-labs/grf#1266] opened 2023-03-04 01:08 UTC
I'm currently running `causal_survival_forest` on an HPC and want to limit the requested resources to 1 thread. Based on the package documentation and closed issues such as #357 and #479, I should be able to do this by setting `num.threads = 1`. However, regardless of the value I've set for `num.threads` (0, 1, 2, ...), my code starts 20 threads (the maximum number available) on the node that my job was sent to. 

Apologies in advance if I've misunderstood how to specify the argument. Either way, I would greatly appreciate any guidance on managing resources used by functions in the `grf` package. 

Thanks! I'm using version 2.2.1, if that's relevant.

**Comment by erikcs** [comment] 2023-03-04 01:48
Hi @janewliang, if you only want to use a single cpu you usually need to allocate a hpc job with just a single cpu. Depending on how the hpc is configured, it might decide to interpret 1 thread as starting redundant threads on all available cpus.

**Comment by janewliang** [comment] 2023-03-04 02:03
@erikcs Thanks for your response! Just to confirm, there is no other argument to control for these sorts of things from the package side, other than `num.threads`?

**Comment by erikcs** [comment] 2023-03-04 02:12
Yes

**Comment by kcgthb** [comment] 2023-03-06 17:41
I can confirm the behavior that `causal_survival_forest()` seems to be partially ignoring `num.threads` and that some portions of the function are starting as many R threads as they are CPUs on the host, no matter what the value of `num.threads` is.

For instance, `causal_survival_forest(... , num.threads = 1)` will start 20 `R` processes when running on a 20-CPU host.

This is a major bug, not only because the `num.threads` parameter is ignored, but more importantly, it prevents proper load control on shared systems.

In HPC environments where resources are shared between users and jobs, this is a significant issue. ​When a user submits a job requesting a single CPU, the scheduler will only allocate one CPU for them. In practice, it will create a kernel cgroup, assign 1 CPU core to this cgroup, and restrict any process started by the job to this cgroup. Meaning that no matter how many threads and processes the job starts, they will all be constrained to that single CPU core. And if many processes start trying to run CPU-heavy tasks, they will all compete for that same CPU core, fight each other, overload that CPU core (which will make the system load spike) and they will each only get a fraction of that CPU's time, resulting in disastrous performance. So not only will the job perform very poorly, take much longer to complete, but it will also have a detrimental effect on the system, and to other users that share it.

In any case, functions that take a `num.threads` parameter should never start more than the specified number of threads/processes.

In the specific case of `causal_survival_forest()`, it looks like some of the functions called are correctly passed the `num.threads` argument (like [`regression_forest`](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/causal_survival_forest.R#LL225-L234C74)), but some others are called either without the argument being passed, or sometimes even reset it to `NULL`:
https://github.com/grf-labs/grf/blob/master/r-package/grf/R/causal_survival_forest.R#L437-L441

Could you please fix those to make sure all the called functions properly inherit the `num.threads` parameter?
Thanks!

**Comment by erikcs** [comment] 2023-03-06 20:42
This sounds more like it has something to do with how sherlock interacts with C++ async threads? The same thing happens if you start a regression_forest with num.threads=1 but allocated the job with more cores available (same with other software that uses C++ async, like [ranger](https://cran.r-project.org/web/packages/ranger/index.html)). The num.threads argument is respected throughout grf on all the machines we've tested it on. Thanks.

**Comment by kcgthb** [comment] 2023-03-06 21:07
Hi @erikcs 

There's no mechanism at the the system level (OS, kernel, or anything else) to control on the number of threads an application can start, unfortunately. It's entirely up to the application to check what resources it can use, or, more importantly, what option the users specified when calling a function.

I'm sure you agree that if the user specifies `num.threads=1`, the program should not start 20 threads, right?

> The num.threads argument is respected throughout grf on all the machines we've tested it on. Thanks.

Evidence seems to show the opposite, I'm afraid. Using the example from the documentation and specifying `num.threads=1` in the call to `causal_survival_forest()` like this:
```
cs.forest <- causal_survival_forest(X, round(Y, 2), W, D, horizon = horizon, num.threads=1)
```
leads to the following process tree:
```
    └─bash,5302,kilian
        └─R,7132
           ├─{R},8112
           ├─{R},8113
           ├─{R},8114
           ├─{R},8115
           ├─{R},8116
           ├─{R},8117
           ├─{R},8118
           ├─{R},8119
           ├─{R},8120
           ├─{R},8121
           ├─{R},8122
           ├─{R},8123
           ├─{R},8124
           ├─{R},8125
           ├─{R},8126
           ├─{R},8127
           ├─{R},8128
           ├─{R},8129
           ├─{R},8130
           └─{R},8131
```
during the execution of `S1.hat <- predict(sf.survival)$predictions` and other calls to `predict()`.

It looks like simply making sure that `num.threads` is passed to all the `predict()` calls in the function would take care of the problem, doesn't it?

**Comment by kcgthb** [comment] 2023-03-06 21:29
By the way, it looks like `ranger` has the same problem: https://github.com/imbs-hl/ranger/issues/513

**Comment by erikcs** [comment] 2023-03-06 21:41
Thanks @kcgthb, I forgot CSF needs to recompute from C++ when doing nuisance prediction, can you please try if running your above example with this version?

```R
devtools::install_github("erikcs/grf", subdir = "r-package/grf", ref = "num-threads-nuisance")
```

**Comment by kcgthb** [comment] 2023-03-06 22:18
@erikcs thanks for the quick fix!
Yes, I can confirm that #1267 fixes the issue, and that `causal_survival_forest()` now respects the `num.threads` option.

Thanks!

**Comment by erikcs** [comment] 2023-03-06 22:33
Thanks for the help @kcgthb! I'll close this now then. @janewliang please use the development version of CSF for now, you can install it with

```R
devtools::install_github("grf-labs/grf", subdir = "r-package/grf")
```
and note that after training the forest, if you do `predict` on a new test set or with estimate.variance=TRUE, you need to pass a num.threads argument.

**Closed by erikcs** 2023-03-06 22:33 UTC
