### ISSUE TITLE
Add support for local linear corrections.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#276] opened 2018-08-04 03:03 UTC
We're planning to support local linear corrections in both `regression_forest` and `causal_forest`, as described in the paper on 'Local Linear Forests' (https://arxiv.org/abs/1807.11408). This is a fairly large project, with several individual tasks.

This work helps address the systematic bias described in #174.

TODO:
- [x] Add local linear corrections to regression prediction. #222
- [x] Automatically select tuning parameters for local linear prediction. #264
- [x] Add separate local linear forest function. #282
- [x] Add local linear corrections to causal prediction. #382 #398 #442
- [ ] Split out the new classes `CausalRelabelingStrategy` and `CausalPredictionStrategy` from `InstrumentalRelabelingStrategy` and `InstrumentalPredictionStrategy`.
- [x] Take local linear corrections into account during regression splitting. #603 #614 
- [ ] Take local linear corrections into account during causal splitting.

**Comment by rajkumarkarthik** [comment] 2018-08-14 04:14
Since we're adding support for multivariate treatments (and instruments), the changes to `InstrumentalRelabelingStrategy `, `InstrumentalPredictionStrategy` etc. should coordinate with #285. Adding that issue here, for reference.

**Comment by rinafriedberg** [comment] 2020-08-21 06:49
LL regression and causal forests are working well; closing out this issue!

**Closed by rinafriedberg** 2020-08-21 06:49 UTC
Labels: 2.0 release, feature
