### ISSUE TITLE
Memory Spike in Causal Forest Estimation

### ISSUE THREAD

**Issue by walterwzhang** [grf-labs/grf#179] opened 2018-02-19 22:53 UTC
Hi,

I've noticed that with the `causal_forest` function the memory spikes during the estimation routine. With a multi-core specification, it the memory spike is right after the cores are done running and processes collapse to a single core. The memory spike also occurs when it is run with one core. In comparison, the `causalForest` function in the [`causalTree` package](https://github.com/susanathey/causalTree) does not have this issue.

For a data set with 300k observations, a binary treatment vector, and a outcome vector, the `causal_forest` function run with 15 cores initially takes ~3.1 GB of memory. Then, as the cores finish and the processes is collapses to one core, the memory spikes past 50 GB. This 50 GB is measured and hard capped by a Slurm job scheduler.

Do you know why the memory spikes at that stage in the `causal_forest` estimation and is there any way to circumvent the memory spike?

This may be vaguely related to [Issue 137](https://github.com/swager/grf/issues/137).

Thank you for your help and for making this package available.

**Comment by jtibshirani** [comment] 2018-02-21 06:15
Hi @walterwzhang, thank you for the ticket! This sounds like a serious bug (and maybe even regression) that we need to look into. To clarify, have you observed this memory spike during the training procedure (`causal_forest`), or during the estimation procedure (`predict`)?

**Comment by walterwzhang** [comment] 2018-02-21 18:50
Thanks @jtibshirani. The memory spike occurs during the training procedure (`causal_forest`). More specifically, it seems that the memory spikes when the code in the `causal_forest` function calls the `instrument_train` function ([this line](https://github.com/swager/grf/blob/93563d4f9be1e939ff3ee55621a46f6f3f516751/r-package/grf/R/causal_forest.R#L110)).

Also, I am running R v3.4.3 with grf v0.9.5 installed from CRAN.

**Comment by swager** [comment] 2019-03-10 18:56
The short story is that, whenever you compute an ATE, you want the final thing you do to be an average of doubly robust scores (see, e.g., Section 2.1 of https://arxiv.org/pdf/1902.07409.pdf). For CATE estimates, a reasonable thing to do is just to average the estimates \hat{tau}(x) from the different forests (this is of course heuristic, and in the long run it'd be better to simply enable the forest to scale to all the data). This is question is on a rather different topic than the original thread; happy to discuss further on a dedicated thread.

**Comment by jtibshirani** [comment] 2019-03-11 00:18
> A related note, would the union forest approach address the memory spike issue. First train X amount of trees, and then update with Y amount of trees.

Unfortunately the ability to union forests will not help with the memory issue. This is because the union method still creates a single forest summary when it combines the individual forests.

**Comment by BryanSWeber** [comment] 2019-03-12 00:32
Curiously, I had a similar issue with regression_forest/instrumental_forest. 

In my particular data set, using the whole data set estimates fine without issue (~7k observations)
But if I use a subset (~5k observations) the memory usage spikes to consume the whole 16GB system and crashed. 

After some careful investigation, I found that I had NA's in my X-variable. Dropping the NA's resolved the problem. I'm not sure why the larger dataset did not have such memory problems or instability, but it may be a good place to look if this is a frequent problem.  It may also be easier to code an NA-catch in terms of solving the problem. @walterwzhang, you may have already checked this carefully, but it's easy mistake to make.

**Comment by jtibshirani** [comment] 2019-09-01 23:46
This work is being tracked in #187. I'm going to close this issue so we can have all discussion in one place.

**Closed by jtibshirani** 2019-09-01 23:46 UTC
Labels: performance
