### ISSUE TITLE
Dataset with a lot of dummys generates NaN predictions

### ISSUE THREAD

**Issue by Isidoro90** [grf-labs/grf#313] opened 2018-10-08 21:56 UTC
Dear developers, 

I have an experiment in banking setup were clients (200k) were randomly assigned for a nudge to increase savings. They received the treatment over 3 months. I have a database that looks like this: 

Y = savings_it
X = A lot of dummys where 1{Has i product} and a few socio-economics varialbes. 

I am trying to learn with dummy treatment interactions have largest treatment effects. However the forest runs but shows NaN predictions when i do 

tau_forest <-causal_forest(X, Y, W)
tau.hat.oob = predict(tau.forest) # produces NaNs

Can you give me light of what might be happening?
How should I handle the longitudinal form of the data (means, new varialbes that show the differences in time?)

**Comment by swager** [comment] 2018-10-14 16:35
This sounds like a bug, thanks for drawing our attention to it. Could you please share a simple simulation with us that replicates the issue, so we can look into it?

**Comment by jtibshirani** [comment] 2018-11-16 05:18
Hi @Isidoro90, I wanted to follow up because we haven't heard from you in a while. Would you be able to provide an example that reproduces the behavior you're describing? If it'd be preferable, you could also send us your script and dataset over email.

**Comment by jtibshirani** [comment] 2018-12-01 20:17
I'm going to close this out because we haven't been able to gather further information, but please feel free to re-open or file a new issue.

**Closed by jtibshirani** 2018-12-01 20:17 UTC
