### ISSUE TITLE
Regression forest trees keep splitting when outcome is constant

### ISSUE THREAD

**Issue by halflearned** [grf-labs/grf#539] opened 2019-10-11 07:02 UTC
**Issue**
When outcome is nonzero and constant, regression forest trees keep producing unnecessary splits. As far as I can tell, this does not happen with causal forests. 

**Example**
```r
set.seed(1)
n <- 1000
X <- matrix(runif(n), n, 1)
Y0 <- rep(0, n)  # Always 0
Y1 <- rep(1, n)  # Always 1

rf1 <- grf::regression_forest(X, Y0)
plot(get_tree(rf1, 1))

rf2 <- grf::regression_forest(X, Y1)
plot(get_tree(rf2, 1))
```

Trees in forest `rf1` does not split at all, as expected. On the other hand, trees in forest `rf2` look like this.

![Screen Shot 2019-10-10 at 11 54 29 PM](https://user-images.githubusercontent.com/20155021/66631051-4b394680-ebba-11e9-9987-b9a7c82f5d86.png)

This bug likely does not affect predictions, but it can cause a performance hit.

**GRF version**
0.10.4

**Comment by erikcs** [comment] 2019-10-24 22:52
Removed bug label since purity check was removed in https://github.com/grf-labs/grf/pull/362

**Comment by erikcs** [comment] 2019-10-26 22:22
@swager pointed out that all the splits are on the edge in `Y1`:  I think this is just an artifact of split candidates being evaluated in sorted order.

Since all Y are the same, the [decrease](https://github.com/grf-labs/grf/blob/master/core/src/splitting/RegressionSplittingRule.cpp#L215) is always the same and the best decrease is set to the Xi who hit that condition first, which in this case are Xi's in sorted order.

**Comment by erikcs** [comment] 2019-11-08 01:10
Closing this for now:

In grf-use you will only have large pure leaves in case of low overlap.

**Closed by erikcs** 2019-11-08 01:10 UTC
Labels: performance
